
export const CATEGORIES_FETCHED_START='CATEGORIES_FETCHED_START';
export const CATEGORIES_FETCHED_SUCCESS='CATEGORIES_FETCHED_SUCCES';
export const CATEGORIES_FETCHED_Faild='CATEGORIES_FETCHED_Faild';
