
export const USER = {
    postLOGIN : "LOGIN_SUCCESS",
    postLOGOUT : "LOGOUT_SUCCESS",
    postUPDATE_USER : "UPDATE_USER",
    postERROR : "ERROR",
};

export const LOGIN = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT_SUCCESS";
export const UPDATE_USER = "UPDATE_USER";
export const ERROR = "ERROR";


export const FETCH_USERS_START = "FETCH_USERS_START";
export const FETCH_USERS_SUCSSES = "FETCH_USERS_SUCSSES";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";


export const ADD_USERS_SUCSSES = "ADD_USERS_SUCSSES";
export const ADD_USERS_ERROR = "ADD_USERS_ERROR";

export const CATEGORY = {
    FETCHED_START:"FETCHED_START",
    CATEGORIES_FETCHED_SUCCESS:"CATEGORIES_FETCHED_SUCCESS",
    CATEGORIES_FETCHED_Faild:"CATEGORIES_FETCHED_Faild",
}
export const CATEGORIES_FETCHED_START = "FETCHED_START";
export const CATEGORIES_FETCHED_SUCCESS = "CATEGORIES_FETCHED_SUCCESS";
export const CATEGORIES_FETCHED_Faild = "CATEGORIES_FETCHED_Faild";



export const GET_TASKS = "GET_TASKS";
